server.port=8081
spring.profiles.active=demo
spring.datasource.url=jdbc:mysql://localhost:3306/arso_productos?serverTimezone=CET&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange=bus
app.rabbitmq.routing-key.usuario-creado=bus.usuarios.usuario-creado
app.rabbitmq.routing-key.usuario-modificado=bus.usuarios.usuario-modificado
app.rabbitmq.routing-key.compraventa-creada=bus.compraventas.compraventa-creada
app.rabbitmq.routing-key.producto-creado=bus.productos.producto-creado
app.rabbitmq.routing-key.producto-modificado=bus.productos.producto-modificado
app.rabbitmq.queue.microservice=productos
app.rabbitmq.binding-pattern.usuarios=bus.usuarios.#
app.rabbitmq.binding-pattern.compraventas=bus.compraventas.#
